export interface IColorPreset {
  name: string;
  hex: string;
}

export const COLOR_PRESETS: IColorPreset[] = [
  { name: 'White', hex: '#FFFFFF' },
  { name: 'Ivory', hex: '#FFFFF0' },
  { name: 'Beige', hex: '#F5F5DC' },
  { name: 'Linen', hex: '#FAF0E6' },
  { name: 'Gainsboro', hex: '#DCDCDC' },
  { name: 'Black', hex: '#000000' },
  { name: 'DimGrey', hex: '#696969' },
  { name: 'Grey', hex: '#BEBEBE' },
  { name: 'DarkGrey', hex: '#A9A9A9' },
  { name: 'LightGray', hex: '#D3D3D3' },
  { name: 'Red', hex: '#FF0000' },
  { name: 'DarkRed', hex: '#8B0000' },
  { name: 'Firebrick', hex: '#B22222' },
  { name: 'IndianRed', hex: '#CD5C5C' },
  { name: 'Maroon', hex: '#B03060' },
  { name: 'Salmon', hex: '#FA8072' },
  { name: 'Orange', hex: '#FFA500' },
  { name: 'DarkOrange', hex: '#FF8C00' },
  { name: 'Coral', hex: '#FF7F50' },
  { name: 'PeachPuff', hex: '#FFDAB9' },
  { name: 'Yellow', hex: '#FFFF00' },
  { name: 'Gold', hex: '#FFD700' },
  { name: 'Goldenrod', hex: '#DAA520' },
  { name: 'Green', hex: '#00FF00' },
  { name: 'DarkGreen', hex: '#006400' },
  { name: 'ForestGreen', hex: '#228B22' },
  { name: 'LimeGreen', hex: '#32CD32' },
  { name: 'OliveDrab', hex: '#6B8E23' },
  { name: 'SeaGreen', hex: '#2E8B57' },
  { name: 'Blue', hex: '#0000FF' },
  { name: 'NavyBlue', hex: '#000080' },
  { name: 'MidnightBlue', hex: '#191970' },
  { name: 'RoyalBlue', hex: '#4169E1' },
  { name: 'DodgerBlue', hex: '#1E90FF' },
  { name: 'SteelBlue', hex: '#4682B4' },
  { name: 'SkyBlue', hex: '#87CEEB' },
  { name: 'LightBlue', hex: '#ADD8E6' },
  { name: 'Purple', hex: '#A020F0' },
  { name: 'Violet', hex: '#EE82EE' },
  { name: 'Orchid', hex: '#DA70D6' },
  { name: 'Lavender', hex: '#E6E6FA' },
  { name: 'Plum', hex: '#DDA0DD' },
  { name: 'Pink', hex: '#FFC0CB' },
  { name: 'LightPink', hex: '#FFB6C1' },
  { name: 'HotPink', hex: '#FF69B4' },
  { name: 'DeepPink', hex: '#FF1493' },
  { name: 'Brown', hex: '#A52A2A' },
  { name: 'SaddleBrown', hex: '#8B4513' },
  { name: 'Chocolate', hex: '#D2691E' },
  { name: 'Tan', hex: '#D2B48C' },
  { name: 'SandyBrown', hex: '#F4A460' },
  { name: 'Burlywood', hex: '#DEB887' },
];
